config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes, only: %i[show index]

  root to: 'recipes#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :find_recipe, only: :show

  def index
    @items = Recipes.all
  end

  def show
    return render file: 'public/404.html', status: :not_found if @item.blank?

    render :show
  end

  private

  def find_recipe
    @item = Recipes.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span>
    </button>
  <%= link_to "Recipes", root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav mr-auto">
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MarleySpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="justify-content d-flex flex-column">
  <%@items.each do |recipe|%>
    <div class="p2">
      <div class="card recipe-list-card">
        <img src="<%= recipe.asset.url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <a href="<%= recipe_path(recipe.id)%>">
            <h5 class="card-title color-black"><%= recipe.title %></h5>
          </a>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/recipes/show.html.erb
<div class="justify-content d-flex flex-column">
  <div class="p2">
    <div class="card recipe-item-card">
      <img src="<%= @item.asset.url %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title color-black"><%= @item.title %></h5>
        <p class="card-text color-black">Tags: <%= @item.tags.map(&:name).join(', ')%></p>
        <p class="card-text color-black"> <%= @item.description %></p>
        <%if @item.chef%>
          <p class="card-text color-black"> Chef: <%= @item.chef.name %> </p>
        <%end%>
      </div>
    </div>
  </div>
</div>